In [1]:
import pandas as pd

**Advanced RAG: Without Retreival**

In [47]:
d.describe()

,Unnamed: 0,error,feedback.dummy,feedback.awrapper,feedback.non_llm_context_precision,feedback.EM,feedback.String_Similarity,feedback.BLUE,feedback.rougeL,execution_time,feedback.correctness,feedback.groundness,feedback.relevance,feedback.retrieval_relevance,feedback.coherence,feedback.llm_context_recall,feedback.llm_context_precision
count,124.000000,0.0,124.0,0.0,124.000000,124.0,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000
mean,61.500000,NaN,0.0,NaN,0.016667,0.0,0.192709,0.022407,0.109074,0.001342,0.214516,0.812903,0.710484,0.795968,0.908871,0.198387,0.505645
std,35.939764,NaN,0.0,NaN,0.081815,0.0,0.089169,0.031238,0.086791,0.000661,0.258102,0.336642,0.260025,0.343203,0.116878,0.248895,0.258923
min,0.000000,NaN,0.0,NaN,0.000000,0.0,0.000000,0.000000,0.000000,0.000444,0.000000,0.000000,0.100000,0.000000,0.300000,0.000000,0.000000
25%,30.750000,NaN,0.0,NaN,0.000000,0.0,0.138991,0.006162,0.058541,0.000882,0.000000,0.900000,0.500000,0.900000,0.900000,0.000000,0.400000
50%,61.500000,NaN,0.0,NaN,0.000000,0.0,0.205217,0.016467,0.095238,0.001069,0.100000,1.000000,0.800000,0.900000,0.900000,0.100000,0.500000
75%,92.250000,NaN,0.0,NaN,0.000000,0.0,0.242832,0.024210,0.142857,0.001634,0.300000,1.000000,0.900000,1.000000,1.000000,0.300000,0.700000
max,123.000000,NaN,0.0,NaN,0.500000,0.0,0.685714,0.215581,0.400000,0.003336,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.900000

**Advanced RAG: With Retreival**

In [45]:
d.describe()

,Unnamed: 0.1,Unnamed: 0,error,feedback.dummy,feedback.awrapper,feedback.non_llm_context_precision,feedback.EM,feedback.String_Similarity,feedback.BLUE,feedback.rougeL,execution_time,feedback.correctness,feedback.groundness,feedback.relevance,feedback.retrieval_relevance,feedback.coherence,feedback.llm_context_recall,feedback.llm_context_precision
count,124.000000,124.000000,0.0,124.0,0.0,124.000000,124.0,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000
mean,61.500000,61.500000,NaN,0.0,NaN,0.015758,0.0,0.195925,0.024471,0.111838,0.000917,0.285081,0.829839,0.837097,0.619355,0.992742,0.333871,0.489516
std,35.939764,35.939764,NaN,0.0,NaN,0.080242,0.0,0.083285,0.030401,0.091040,0.000499,0.307295,0.302020,0.257084,0.371916,0.080822,0.337828,0.351262
min,0.000000,0.000000,NaN,0.0,NaN,0.000000,0.0,0.000000,0.000000,0.000000,0.000378,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000
25%,30.750000,30.750000,NaN,0.0,NaN,0.000000,0.0,0.141494,0.005188,0.038503,0.000550,0.000000,0.800000,0.700000,0.200000,1.000000,0.000000,0.000000
50%,61.500000,61.500000,NaN,0.0,NaN,0.000000,0.0,0.200000,0.017592,0.100633,0.000759,0.200000,1.000000,1.000000,0.800000,1.000000,0.200000,0.600000
75%,92.250000,92.250000,NaN,0.0,NaN,0.000000,0.0,0.249102,0.030793,0.174552,0.001135,0.500000,1.000000,1.000000,0.900000,1.000000,0.600000,0.800000
max,123.000000,123.000000,NaN,0.0,NaN,0.500000,0.0,0.454545,0.159252,0.375000,0.002621,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

**Naive RAG**

In [6]:
d.describe()

,Unnamed: 0,feedback.non_llm_context_recall,feedback.non_llm_context_precision,feedback.EM,feedback.String_Similarity,feedback.BLUE,feedback.rougeL,execution_time,feedback.correctness,feedback.groundness,feedback.relevance,feedback.retrieval_relevance,feedback.coherence,feedback.llm_context_recall,feedback.llm_context_precision
count,122.000000,121.000000,121.000000,121.0,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000,121.000000
mean,60.500000,0.016804,0.010216,0.0,0.173437,0.021831,0.082977,0.000804,0.188430,0.876033,0.647934,0.860331,0.912397,0.213223,0.524793
std,35.362409,0.084997,0.053904,0.0,0.088542,0.037897,0.093268,0.000425,0.222182,0.283144,0.301137,0.289390,0.125546,0.257210,0.239889
min,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000349,0.000000,0.000000,0.000000,0.000000,0.200000,0.000000,0.000000
25%,30.250000,0.000000,0.000000,0.0,0.115942,0.000000,0.000000,0.000480,0.000000,0.900000,0.500000,0.900000,0.900000,0.000000,0.400000
50%,60.500000,0.000000,0.000000,0.0,0.174603,0.011412,0.071429,0.000649,0.100000,1.000000,0.800000,1.000000,0.900000,0.100000,0.500000
75%,90.750000,0.000000,0.000000,0.0,0.231454,0.028449,0.127660,0.001000,0.300000,1.000000,0.900000,1.000000,1.000000,0.300000,0.700000
max,121.000000,0.500000,0.333333,0.0,0.468750,0.234624,0.400000,0.002344,0.900000,1.000000,1.000000,1.000000,1.000000,1.000000,0.900000